2017-01-28T08:22:09.238-0800 I CONTROL  [initandlisten] MongoDB starting : pid=73 port=27017 dbpath=/data/db 64-bit host=TROUT-LAPTOP
2017-01-28T08:22:09.238-0800 I CONTROL  [initandlisten] db version v3.2.11
2017-01-28T08:22:09.238-0800 I CONTROL  [initandlisten] git version: 009580ad490190ba33d1c6253ebd8d91808923e4
2017-01-28T08:22:09.238-0800 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
2017-01-28T08:22:09.238-0800 I CONTROL  [initandlisten] allocator: tcmalloc
2017-01-28T08:22:09.238-0800 I CONTROL  [initandlisten] modules: none
2017-01-28T08:22:09.238-0800 I CONTROL  [initandlisten] build environment:
2017-01-28T08:22:09.238-0800 I CONTROL  [initandlisten]     distmod: ubuntu1604
2017-01-28T08:22:09.238-0800 I CONTROL  [initandlisten]     distarch: x86_64
2017-01-28T08:22:09.239-0800 I CONTROL  [initandlisten]     target_arch: x86_64
2017-01-28T08:22:09.239-0800 I CONTROL  [initandlisten] options: {}
2017-01-28T08:22:09.268-0800 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2017-01-28T08:22:09.268-0800 W -        [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
2017-01-28T08:22:09.268-0800 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2017-01-28T08:22:09.269-0800 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=6G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-01-28T08:22:09.703-0800 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-01-28T08:22:09.703-0800 I CONTROL  [initandlisten] 
2017-01-28T08:22:09.732-0800 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
2017-01-28T08:22:09.732-0800 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2017-01-28T08:22:09.737-0800 I NETWORK  [initandlisten] waiting for connections on port 27017
2017-01-28T08:22:10.046-0800 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
2017-01-28T08:56:49.051-0800 E NETWORK  [initandlisten] can't get TCP_KEEPIDLE: errno:22 Invalid argument
2017-01-28T08:56:49.051-0800 E NETWORK  [initandlisten] can't get TCP_KEEPINTVL: errno:22 Invalid argument
2017-01-28T08:56:49.051-0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:59783 #1 (1 connection now open)
2017-01-28T08:56:49.097-0800 E NETWORK  [initandlisten] can't get TCP_KEEPIDLE: errno:22 Invalid argument
2017-01-28T08:56:49.097-0800 E NETWORK  [initandlisten] can't get TCP_KEEPINTVL: errno:22 Invalid argument
2017-01-28T08:56:49.098-0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:59784 #2 (2 connections now open)
2017-01-28T08:56:49.098-0800 E NETWORK  [initandlisten] can't get TCP_KEEPIDLE: errno:22 Invalid argument
2017-01-28T08:56:49.098-0800 E NETWORK  [initandlisten] can't get TCP_KEEPINTVL: errno:22 Invalid argument
2017-01-28T08:56:49.098-0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:59785 #3 (3 connections now open)
2017-01-28T08:56:49.098-0800 E NETWORK  [initandlisten] can't get TCP_KEEPIDLE: errno:22 Invalid argument
2017-01-28T08:56:49.098-0800 E NETWORK  [initandlisten] can't get TCP_KEEPINTVL: errno:22 Invalid argument
2017-01-28T08:56:49.098-0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:59786 #4 (4 connections now open)
2017-01-28T08:56:49.098-0800 E NETWORK  [initandlisten] can't get TCP_KEEPIDLE: errno:22 Invalid argument
2017-01-28T08:56:49.098-0800 E NETWORK  [initandlisten] can't get TCP_KEEPINTVL: errno:22 Invalid argument
2017-01-28T08:56:49.098-0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:59787 #5 (5 connections now open)
2017-01-28T09:45:42.822-0800 I NETWORK  [conn1] end connection 127.0.0.1:59783 (4 connections now open)
2017-01-28T09:45:42.822-0800 I NETWORK  [conn2] end connection 127.0.0.1:59784 (4 connections now open)
2017-01-28T09:45:42.823-0800 I NETWORK  [conn3] end connection 127.0.0.1:59785 (4 connections now open)
2017-01-28T09:45:42.823-0800 I NETWORK  [conn4] end connection 127.0.0.1:59786 (4 connections now open)
2017-01-28T09:45:42.823-0800 I NETWORK  [conn5] end connection 127.0.0.1:59787 (2 connections now open)
2017-01-28T09:45:50.510-0800 E NETWORK  [initandlisten] can't get TCP_KEEPIDLE: errno:22 Invalid argument
2017-01-28T09:45:50.511-0800 E NETWORK  [initandlisten] can't get TCP_KEEPINTVL: errno:22 Invalid argument
2017-01-28T09:45:50.511-0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:61807 #6 (1 connection now open)
2017-01-28T09:45:50.557-0800 E NETWORK  [initandlisten] can't get TCP_KEEPIDLE: errno:22 Invalid argument
2017-01-28T09:45:50.557-0800 E NETWORK  [initandlisten] can't get TCP_KEEPINTVL: errno:22 Invalid argument
2017-01-28T09:45:50.557-0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:61808 #7 (2 connections now open)
2017-01-28T09:45:50.557-0800 E NETWORK  [initandlisten] can't get TCP_KEEPIDLE: errno:22 Invalid argument
2017-01-28T09:45:50.558-0800 E NETWORK  [initandlisten] can't get TCP_KEEPINTVL: errno:22 Invalid argument
2017-01-28T09:45:50.558-0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:61809 #8 (3 connections now open)
2017-01-28T09:45:50.558-0800 E NETWORK  [initandlisten] can't get TCP_KEEPIDLE: errno:22 Invalid argument
2017-01-28T09:45:50.558-0800 E NETWORK  [initandlisten] can't get TCP_KEEPINTVL: errno:22 Invalid argument
2017-01-28T09:45:50.558-0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:61810 #9 (4 connections now open)
2017-01-28T09:45:50.558-0800 E NETWORK  [initandlisten] can't get TCP_KEEPIDLE: errno:22 Invalid argument
2017-01-28T09:45:50.558-0800 E NETWORK  [initandlisten] can't get TCP_KEEPINTVL: errno:22 Invalid argument
2017-01-28T09:45:50.558-0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:61811 #10 (5 connections now open)
